# CodeRabbit Configuration
# https://docs.coderabbit.ai/reference/configuration

language: "ja"

reviews:
  profile: chill
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  sequence_diagrams: true
  review_status: true
  commit_status: true
  changed_files_summary: true
  poem: false

  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: false
    ignore_title_keywords:
      - wip
      - draft

  path_filters:
    - "!node_modules/**"
    - "!**/__pycache__/**"
    - "!**/*.pyc"
    - "!dist/**"
    - "!.next/**"
    - "!**/package-lock.json"
    - "!**/poetry.lock"

tools:
  ruff:
    enabled: true
  eslint:
    enabled: true
  gitleaks:
    enabled: true

knowledge_base:
  opt_out: false
  code_guidelines:
    enabled: true
    filePatterns:
      - "**/CLAUDE.md"

chat:
  auto_reply: true
